name: GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy_page:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install -r aisg-context/guide-site/requirements.txt
      - run: mkdocs gh-deploy --force
